### ISSUE TITLE
selenium.common.exceptions.NoSuchElementException

### ISSUE THREAD

**Issue by edwardnguyen1705** [frederikme/GoogleImageScraper#1]
Dear @frederikme ,

When I try your program this error appears

```
Getting ChromeDriver ...
 
[WDM] - Current google-chrome version is 87.0.4280
[WDM] - Get LATEST driver version for 87.0.4280
[WDM] - Driver [/Users/thanhnguyen/.wdm/drivers/chromedriver/mac64/87.0.4280.88/chromedriver] found in cache
Traceback (most recent call last):
  File "quickstart.py", line 4, in <module>
    scraper = GoogleImageScraper()
  File "/Users/thanhnguyen/Documents/Datasets/unlabelledPeople/GoogleImageScraper/scraper.py", line 44, in __init__
    self.acceptPolicies()
  File "/Users/thanhnguyen/Documents/Datasets/unlabelledPeople/GoogleImageScraper/scraper.py", line 231, in acceptPolicies
    self.browser.find_element_by_xpath('//*[@id="cnsw"]/iframe'))
  File "/Users/thanhnguyen/.pyenv/versions/3.6.8/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/thanhnguyen/.pyenv/versions/3.6.8/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/thanhnguyen/.pyenv/versions/3.6.8/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/thanhnguyen/.pyenv/versions/3.6.8/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="cnsw"]/iframe"}
  (Session info: chrome=87.0.4280.88)
```

Do you have any suggestion?

**Comment by frederikme** [comment]
Hi @edwardnguyen1705,

The issue is caused by one of the following options: 
- Policies pop up isn't displayed (depending on what country your from)
- It tries to access the popup before it's being displayed (due to latency/wifi)
- The policies are being displayed in another language than English. 

If it's one of the first two problems, the issue should be solved by pulling the latest version. 
I added a TryExcept around the switching to iframe and a WebDriverWait to solve the possible wifi issues.

If the bug persists. Feel free to open a new issue.

Greetings,
Fred
